/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AssetManager: typeof import('./src/components/AssetManager.vue')['default']
    BatchActions: typeof import('./src/components/subscription/BatchActions.vue')['default']
    CodeEditor: typeof import('./src/components/CodeEditor.vue')['default']
    ConfirmModal: typeof import('./src/components/common/ConfirmModal.vue')['default']
    ConversionSettings: typeof import('./src/components/settings/ConversionSettings.vue')['default']
    DataTable: typeof import('./src/components/common/DataTable.vue')['default']
    EntityForm: typeof import('./src/components/common/EntityForm.vue')['default']
    GeneralSettings: typeof import('./src/components/settings/GeneralSettings.vue')['default']
    GroupManagement: typeof import('./src/components/subscription/GroupManagement.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    NText: typeof import('naive-ui')['NText']
    ProfileForm: typeof import('./src/components/settings/ProfileForm.vue')['default']
    ProfileRulesManager: typeof import('./src/components/settings/ProfileRulesManager.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleDataTable: typeof import('./src/components/common/SimpleDataTable.vue')['default']
    SubscriptionForm: typeof import('./src/components/subscription/SubscriptionForm.vue')['default']
    SubscriptionList: typeof import('./src/components/subscription/SubscriptionList.vue')['default']
    SubscriptionLogModal: typeof import('./src/components/SubscriptionLogModal.vue')['default']
    SubscriptionNodesPreview: typeof import('./src/components/SubscriptionNodesPreview.vue')['default']
  }
}
